[network]
badge_url=http://localhost:5000
face_socket_url=http://localhost:5001
face_api_url=http://localhost:5050
mjpeg_url=http://localhost:5050/video_feed

[display]
; Rotation en degrés : 0 | 90 | 180 | 270
rotation=90
width=600
height=1024

[app]
admin_password=2899100*-+
; Délai d'affichage de la carte accès en ms
event_display_ms=5000
